image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - integration
  - prod

job:
  stage: build
  script:
    - docker pull bkimminich/juice-shop
    - docker run --rm -p 3000:3000 bkimminich/juice-shop
